name: Environment build demo
env:
  CURRENT_ENV: staging
run-name: ${{ github.actor }} build
on:
  - workflow_dispatch

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check for production
        run: |
          echo "gh head ref $GITHUB_HEAD_REF"
          echo "gh ref $GITHUB_REF"