name: Environment build demo
run-name: ${{ github.actor }} build
on:
  - workflow_dispatch

jobs:
  select-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.env_check.outputs.env_name }}
    steps:
      - name: Environment Check
        id: env_check
        run: |
          echo "Current branch: ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          else
            echo "env_name=staging" >> $GITHUB_OUTPUT
          fi

  print-environment:
    runs-on: ubuntu-latest
    needs: select-environment
    steps:
      - name: Print environment
        run: |
          echo "Environment: ${{ needs.select-environment.outputs.env_name }}"

  print-hello-world:
    runs-on: ubuntu-latest
    needs: select-environment
    environment: ${{ needs.select-environment.outputs.env_name }}
    steps:
      - name: Print hello world
        run: |
          echo "Result: ${{ vars.HELLO_WORLD }}"