name: Koa Demo Build
run-name: ${{ github.actor }} triggered build
on: [push]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job automatically triggered by ${{ github.event_name }} event"
      - run: echo "Job is now running on ${{ runner.os }} server in github"
      - run: echo "Job is running for branch ${{ github.ref }} in repository ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} has been cloned to the runner"
      - name: Build Koa Demo App
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - run: echo "This job's status is ${{ job.status }}"