name: Environment build demo
env:
  CURRENT_ENV: staging
run-name: ${{ github.actor }} build
on:
  - workflow_dispatch

jobs:
  select-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Environment Check
        id: env_check
        run: |
          echo "Current branch: ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "env_name==production" >> $GITHUB_OUTPUT
          else
            echo "env_name==staging" >> $GITHUB_OUTPUT
          fi

  print-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: |
          echo "Env: ${{ steps.select-environment.outputs.env_name }}"