name: Environment build demo
env:
  CURRENT_ENV: staging
run-name: ${{ github.actor }} build
on:
  - workflow_dispatch

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Which Environment
        run: $CURRENT_ENV = "Staging"